name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Change if using a different branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use latest LTS version

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install
        continue-on-error: false

      - name: Build Next.js App
        run: |
          echo "Building Next.js..."
          npm run build && npm run export
        continue-on-error: false

      - name: List Output Files
        run: |
          echo "Listing output files in 'out' directory..."
          ls -la out

      # ✅ FIX: Use the latest version of upload-artifact
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4  # ✅ Updated to v4
        with:
          name: nextjs-build
          path: out  # Next.js exports static files to `out`

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2  # ✅ Correct version for GitHub Pages

      - name: Deployment Success Message
        run: echo "✅ Deployment completed! Check your site at https://asjidale.github.io/your-repo-name/"
